from rocker/rstudio:3.5.3

RUN apt update && \
      apt install -y libgit2-dev zlib1g-dev libxml2-dev && \
      rm -rf /var/lib/apt/lists/*

RUN R -e 'install.packages("bitops")'
RUN R -e 'install.packages("XML")'
RUN R -e 'install.packages("RCurl")'
RUN R -e 'install.packages("devtools")'

COPY .Renviron /home/rstudio/.Renviron
